### ISSUE TITLE
ext4 브랜치 관련

### ISSUE THREAD

**Issue by YoungHoonJun** [EMDC-OS/pm-opzero#1]
논문에 작성되어 있는 디자인과 master branch의 동작이 다르게 보입니다. ext4 브랜치가 원래 의도한 디자인이 맞을까요? 별도의 안내가 없어서 문의 드립니다.

**Comment by J-S-Kim** [comment]
Usage에 적혀있는 것과 같이 master branch가 아니라
원하는 파일시스템에 따라 ext4 및 xfs branch를 적절히 선택해야 합니다.

헷갈리지 않게 README를 좀 눈에 띄게 수정했습니다.
