### ISSUE TITLE
XFS 파일시스템 실험 방법

### ISSUE THREAD

**Issue by bobsiunn** [EMDC-OS/pm-opzero#2]
논문의 evaluation에 있는 XFS 관련 실험을 재현하고 싶습니다. 혹시 XFS 파일시스템에서 실험을 수행하려면 어떻게 해야하나요?

**Comment by J-S-Kim** [comment]
Usage에 적혀있는 것과 같이 master branch가 아니라
원하는 파일시스템에 따라 ext4 및 xfs branch를 적절히 선택해야 합니다.

헷갈리지 않게 README를 좀 눈에 띄게 수정했습니다.
